### ISSUE TITLE
Four suggestions

### ISSUE THREAD

**Issue by kth1207** [HiTyra/Project#1]
Hey Tyra. 

I can relate to your site a lot because I have actually been to Bali when I was young, so it was really interesting to see some of the places that I have been to like the Rice Farm. Overall I think your site looks great, but since I have to make suggestions, here are some that could be helpful. 

Content : 
1) I feel like you can be a little more descriptive with the content. For example, giving a more detailed description of where you can experience the rafting, and maybe adding more photos related to the activity. Same goes for other pages of your website. 

2) I feel like placing your index page navigation bar in the same place as the rest of the pages would be better. 

Technical : 
1) I don't know if you did this on purpose but adjusting the size of the index page's navigation bar to fit all the options in one line would make the page look better. 

2) You also might be thinking of adding more content in the contact page, but if you are not, it may be better to have the form in the middle of the page.

**Comment by HiTyra** [comment]
thanks!
